language: node_js
node_js:
  - node
os: osx
git:
  depth: 3
branches:
  only:
    - master
before_install:
  - brew install wine rpm
install:
  - npm install
  - npm run postinstall:dev
cache:
  directories:
    - node_modules
script:
  - npm run deploy
deploy:
  provider: releases
  api_key:
    secure: DNjzANF11SKjNatxQVNbHQXh2T8xic28nD/ogaWN4pRPq2oN+SI4Von21bGkuifQ7l9tLnCSvBnuUHZtwWtXJKH8DREzbfAF5nV73c0K0n3WTg29NjZi4s09OMI7frQ/4TjdRYMusbN+nwEQudj0vFsscxuFSmCMNAsBUipnElEzEs6//z6Janx1++Xm+XP/MhXN7gK3wgOkrtLrchhPG3kuhimPmJf55XwJzEtwb9QqS5F5+yuq+y9G+oejAetV+936zJCF60djREXukoTN+UiuX2oZ+0HhmklwtSMcIDNo30S9WvrcnFLuip7nqFbGqLeQaCt/iv8QM2L58snE3SWyv9bIeJiecLHZu3N5Tz4wTO7gteZY4IF3ysUcYrJWZNap6BP8L7D/319usbhaOfLfQ6YR8CdrIkH4KINKIa+QYoC84Pn5EffHpcg5HcOge6yTO0twx+jmGDQ/ro3gAfPe1mpJC8+6xHCLm11OqdWHecTZqcx/r2DJK6cgj/JctJIwuKgC/aQDSI3fyrCw5nJeNgNtrbHNr714vlcO+pVBjXR5llwYE+EgcDE7GTfVEaZUstm5XGLQ5F3DBXPQ/Hror+9TPfSJEq/EVGld4zsVnw55vlCJyXBjRtA5B+uwXrq/yywxSC3/5OpiRN2p9+DfctUAglhkhw47vlnfMSU=
  file_glob: true
  skip_cleanup: true
  file:
    - "build/*.exe"
    - "build/*.zip"
    - "build/*.dmg"
    - "build/*.AppImage"
    - "build/*.deb"
    - "build/*.rpm"
    - "build/*.pacman"
    - "build/*.tar.xz"
  on:
    tags: true
