appId: "com.gmail.junehanabi.pokered-save-editor"
productName: "Pokered Save Editor"
copyright: "Copyright © 2018 June Hanabi"

directories:
  buildResources: "dist"
  output: "build"

files:
  - "./dist/**/*"
  - "./electron/**/*"
  - "./main.js"

asar: false
